config/routes.rb
Rails.application.routes.draw do
  root to: 'puzzles#index'
  resources 'puzzles', only: [:show]
  resources 'scores', only: [:index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :puzzle
end

app/models/puzzle.rb
class Puzzle < ApplicationRecord
  has_many :characters
  has_many :scores
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :puzzle
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/puzzles_controller.rb
class PuzzlesController < ApplicationController
  def index
    @puzzles = Puzzle.all
  end

  def show
    @puzzle = Puzzle.find(params[:id])
    @puzzle_id = @puzzle.id
    @score = Score.new
    respond_to do |format|
      format.html
      format.json { render json: @puzzle.characters }
    end
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def index
    @puzzle = Puzzle.find(params[:puzzle_id])
    @scores = @puzzle.scores.order("score")
  end

  def create
    @score = Score.new(score_params)
    @puzzle = Puzzle.find(params[:score][:puzzle_id])
    if @score.save
      redirect_to scores_path(:puzzle_id => @puzzle.id)
    end
  end

  private
  def score_params
    params.require(:score).permit(:name, :puzzle_id, :score)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/puzzles_helper.rb
module PuzzlesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Where's Waldo?</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <%= yield %>
  </body>
</html>

app/views/puzzles/index.html.erb
<h1 class="index-heading">Where's Waldo?</h1>
<h3 class="index-heading">Select a puzzle below to begin</h3>

<div class="puzzles-container">
  <% @puzzles.each do |puzzle| %>
    <div class="select-puzzle">
      <h1><%= link_to puzzle.name, puzzle_path(puzzle) %></h1>
      <%= link_to image_tag(puzzle.image_url, class: "puzzle-preview"), puzzle_path(puzzle) %>
    </div>
  <% end %>
</div>

app/views/puzzles/show.html.erb
<div class="puzzle <%= controller_name %>" id="<%= @puzzle_id %>">
  <div class="heading">
    <h1><%= @puzzle.name %></h1>
    <h3 id="timer"></h3>
    <h1><%= link_to "Back To Puzzles", root_path %></h1>
  </div>
  <div class="selection-menu closed">
    <div>Who is this?</div>
    <% @puzzle.characters.each do |character| %>
      <button><%= character.name %></button>
    <% end %>
  </div>
  <div class="success message closed">
    <div>Good job!</div>
  </div>
  <div class="try-again message closed">
    <div>Try again!</div>
  </div>
  <div class="submit-score closed">
    <div>You found everyone! Submit your score below.</div>
    <div class="score"></div>
    <div class="score-form">
      <%= form_for(@score) do |f| %>
        <div><%= f.hidden_field :puzzle_id, :value => @puzzle.id %></div>
        <div>
          <%= f.label :name, "Name:" %>
          <%= f.text_field :name %>
        </div>
        <div>
          <%= f.label :score, "Score:" %>
          <%= f.text_field :score, :readonly => true %>
        </div>
        <%= f.submit "Submit" %>
      <% end %>
    </div>
  </div>
  <% @puzzle.characters.each do |character| %>
    <div class="<%= character.name %> marker closed"></div>
  <% end %>
  <%= image_tag(@puzzle.image_url, class: "puzzle-image") %>
  <div id="remaining-characters">
    <h5>Characters Left:<h5>
    <% @puzzle.characters.each do |character| %>
      <div class="remaining-character" id="<%= character.name %>">
        <%= image_tag(character.name, class: "character-image") %>
      </div>
    <% end %>
  </div>
</div>

app/views/scores/index.html.erb
<h4><%= link_to "Play again", root_path %></h4>
<h1>Scores for "<%= @puzzle.name %>" Puzzle</h1>
<div id="scoreboard">
  <div class="score-div" id="scores-heading">
    <div class="name">Name</div>
    <div class="score">Score</div>
  </div>
  <% @scores.each do |score| %>
    <div class="score-div">
      <div class="name"><%= score.name %></div>
      <div class="score"><%= score.score %></div>
    </div>
  <% end %>
</div>